package resources

var TestAntiAffinityRule = newYamlFile("yamls/testAntiAffinityRule.yaml")
var PluginsInitContainer = newYamlFile("yamls/pluginsInitContainer.yaml")
var AcceptLicenseAgreementBoolYes = newYamlFile("yamls/acceptLicenseAgreementBoolYes.yaml")
var AcceptLicenseAgreementBoolTrue = newYamlFile("yamls/acceptLicenseAgreementBoolTrue.yaml")
var AcceptLicenseAgreement = newYamlFile("yamls/acceptLicenseAgreement.yaml")
var ApocCorePlugin = newYamlFile("yamls/apocCorePlugin.yaml")
var CsvMetrics = newYamlFile("yamls/csvMetrics.yaml")
var DefaultStorageClass = newYamlFile("yamls/defaultStorageClass.yaml")
var JvmAdditionalSettings = newYamlFile("yamls/jvmAdditionalSettings.yaml")
var BoolsInConfig = newYamlFile("yamls/boolsInConfig.yaml")
var IntsInConfig = newYamlFile("yamls/intsInConfig.yaml")
var ChmodInitContainer = newYamlFile("yamls/chmodInitContainer.yaml")
var ChmodInitContainerAndCustomInitContainer = newYamlFile("yamls/chmodInitContainerAndCustomInitContainer.yaml")
var ReadReplicaUpstreamStrategy = newYamlFile("yamls/read_replica_upstream_selection_strategy.yaml")
var ExcludeLoadBalancer = newYamlFile("yamls/excludeLoadBalancer.yaml")
var EmptyImageCredentials = newYamlFile("yamls/imagePullSecret/emptyImageCreds.yaml")
var DuplicateImageCredentials = newYamlFile("yamls/imagePullSecret/duplicateImageCreds.yaml")
var MissingImageCredentials = newYamlFile("yamls/imagePullSecret/missingImageCreds.yaml")
var EmptyImagePullSecrets = newYamlFile("yamls/imagePullSecret/emptyImagePullSecrets.yaml")
var InvalidNodeSelectorLabels = newYamlFile("yamls/nodeselector.yaml")
var ApocConfig = newYamlFile("yamls/apocConfig.yaml")
var ApocClusterTestConfig = newYamlFile("yamls/apocClusterTest.yaml")
var PodSpecAnnotations = newYamlFile("yamls/podSpecAnnotations.yaml")
var StatefulSetAnnotations = newYamlFile("yamls/statefulSetAnnotations.yaml")
var PriorityClassName = newYamlFile("yamls/priorityClassName.yaml")
