{{- $defaultSpec := include "neo4j.services.neo4j.defaultSpec" . | fromYaml }}
{{- $spec := get $defaultSpec .Values.spec.type | merge .Values.spec  }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "neo4j.name" $ }}-lb-neo4j"
  namespace: "{{ .Release.Namespace }}"
  labels:
    helm.neo4j.com/neo4j.name: "{{ template "neo4j.name" $ }}"
    app: "{{ template "neo4j.name" . }}"
    helm.neo4j.com/service: "neo4j"
    {{- include "neo4j.labels" .Values.neo4j | indent 4 }}
  annotations:
  {{- include "neo4j.annotations" $.Values.annotations | indent 4 }}
spec:
  {{- if $.Values.multiCluster }}
  publishNotReadyAddresses: true
  {{- end }}
  type: "{{ $.Values.spec.type | required "service type must be specified" }}"
  {{- omit $spec "type" "ports" "selector" | include "neo4j.services.extraSpec"  | nindent 2 }}
  ports:
    {{- with .Values.ports }}
    {{- if .http.enabled }}
    - protocol: TCP
      port: {{ .http.port | default 7474 }}
      targetPort: {{ .http.targetPort | default 7474 }}
      name: {{ .http.name | default "http" }}
    {{- end }}
    {{- if .https.enabled }}
    - protocol: TCP
      port: {{ .https.port | default 7473 }}
      targetPort: {{ .https.targetPort | default 7473 }}
      name: {{ .https.name | default "https" }}
    {{- end }}
    {{- if .bolt.enabled }}
    - protocol: TCP
      port: {{ .bolt.port | default 7687 }}
      targetPort: {{ .bolt.targetPort | default 7687 }}
      name: {{ .bolt.name | default "tcp-bolt" }}
    {{- end }}
    {{- if .backup.enabled }}
    - protocol: TCP
      port: {{ .backup.port | default 6362 }}
      targetPort: {{ .backup.targetPort | default 6362 }}
      name: {{ .backup.name | default "tcp-backup" }}
    {{- end }}
    {{- end }}
    {{/* this condition opens internal ports only when multi-k8s-cluster is enabled */}}
    {{- if .Values.multiCluster }}
    - name: tcp-boltrouting
      protocol: TCP
      port: 7688
      targetPort: 7688
    - name: tcp-discovery
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: tcp-raft
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: tcp-tx
      protocol: TCP
      port: 6000
      targetPort: 6000
    {{- end }}
  selector:
    app: "{{ template "neo4j.name" . }}"
    {{- with .Values.selector }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
