#!/usr/bin/env bash

if [ -f ./devenv.local ]; then
    . ./devenv.local
    export CLOUDSDK_CORE_PROJECT
    export CLOUDSDK_COMPUTE_ZONE
    export CLOUDSDK_COMPUTE_REGION
    export CLOUDSDK_CONTAINER_CLUSTER
    export PACKAGE_SIGNING_KEY
    export AWS_CLUSTER_NAME
    export AWS_NODE_GROUP_NAME
    export AWS_DEFAULT_REGION
    export AWS_AZ
    export PUBLIC_KEY_PATH
    export AWS_KEY_ID
    export AWS_ACCESS_KEY
else
    echo "Couldn't find ./devenv.local."
fi

# Add scripts to path
export PATH=${PATH}:./bin

# Use a local kubeconfig
KUBECONFIG=".kube/config"
if [ -f ~/.kube/config ]; then
    cp ~/.kube/config "${KUBECONFIG}"
fi
export KUBECONFIG
