{{- $isEnterprise := required "neo4j.edition must be specified" .Values.neo4j.edition | regexMatch "(?i)enterprise" -}}
{{- $authDisabled := index .Values.config "dbms.security.auth_enabled" | default "" | regexMatch "(?i)no|false" -}}
{{- $offlineMaintenanceEnabled :=  .Values.neo4j.offlineMaintenanceModeEnabled }}
{{- $neo4jImage := include "neo4j.image" . }}

{{- template "neo4j.checkLicenseAgreement" . -}}

{{- range $name, $spec := .Values.volumes -}}

  {{- range $otherName, $otherSpec := $.Values.volumes -}}
    {{- if ne $otherName $name}}
      {{- if eq $spec.mode $otherSpec.mode }}
        {{- if eq $spec.mode "volume" }}
          {{- if and $spec.volume.persistentVolumeClaim $otherSpec.volume.persistentVolumeClaim }}
            {{- if eq $spec.volume.persistentVolumeClaim.claimName $otherSpec.volume.persistentVolumeClaim.claimName }}
              {{ cat "Cannot mount the same persistent volume claim multiple times:" $name "and" $otherName "use the same persistent volume claim!" | fail }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end}}
  {{- end }}
{{- end }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    helm.neo4j.com/neo4j.name: "{{ template "neo4j.name" $ }}"
    app: "{{ template "neo4j.appName" . }}"
    helm.neo4j.com/instance: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  serviceName: "{{ .Release.Name }}"
  podManagementPolicy: "Parallel" # This setting means that the StatefulSet controller doesn't block applying changes until the existing Pod is READY.
  replicas: 1
  selector:
    matchLabels:
      app: "{{ template "neo4j.appName" . }}"
  template:
    metadata:
      labels:
        app: "{{ template "neo4j.appName" . }}"
        helm.neo4j.com/pod_category: "neo4j-instance" # used for anti affinity rules
        helm.neo4j.com/instance: "{{ .Release.Name }}"
      annotations:
        "checksum/{{ .Release.Name }}-config": {{ include (print $.Template.BasePath "/neo4j-config.yaml") . | sha256sum }}
    spec:
      {{- if .Values.podSpec.podAntiAffinity }}
      affinity:
        {{- if kindIs "bool" .Values.podSpec.podAntiAffinity | and .Values.podSpec.podAntiAffinity }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: "{{ template "neo4j.appName" . }}"
                  helm.neo4j.com/pod_category: "neo4j-instance"
              topologyKey: kubernetes.io/hostname
        {{- else }}
        podAntiAffinity: {{ toYaml .Values.podSpec.podAntiAffinity | nindent 10 }}
        {{- end }}
      {{- end }}
      serviceAccountName: "{{ .Release.Name }}"
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ if $offlineMaintenanceEnabled  }}0{{ else }}{{ .Values.podSpec.terminationGracePeriodSeconds }}{{ end }}
      {{- $initContainers := .Values.podSpec.initContainers }}
      {{- $initChmodContainer := include "neo4j.initChmodContainer" . }}
      {{- if $initChmodContainer }}{{ $initContainers = fromYaml $initChmodContainer | prepend $initContainers }}{{ end }}
      {{- with $initContainers }}
      initContainers:
        {{- range $i, $initContainer := . }}
        - {{ $initContainer | toYaml | indent 10 | trimAll " " }}
          {{- if not ( hasKey $initContainer "image") }}
          image: "{{ $neo4jImage }}"
          {{- end }}
          {{- if not ( hasKey $initContainer "volumeMounts") }}
          volumeMounts: {{ include "neo4j.volumeMounts" ( omit $.Values.volumes "logs" "metrics" ) | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: "neo4j"
          image: "{{ $neo4jImage }}"
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          {{- if $offlineMaintenanceEnabled }}
          command:
            - "bash"
            - "-c"
            - "while true; do echo 'Neo4j is not running. Pod is in offline maintenance mode. Remove neo4j.offlineMaintenanceModeEnabled setting and run `helm upgrade ...` to resume normal operation.'; sleep 60; done"
          {{- end }}
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-env"
            {{- if not $authDisabled }}
            - secretRef:
                name: "{{ .Release.Name }}-auth"
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NEO4J_ADMIN
              value: "{{ .Release.Name }}-admin.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
            - name: SERVICE_NEO4J_INTERNALS
              value: "{{ .Release.Name }}-internals.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
            - name: SERVICE_NEO4J
              value: "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
            - containerPort: 6362
              name: backup
          securityContext: {{ omit .Values.securityContext "fsGroupChangePolicy" "fsGroup" | toYaml  | nindent 14 }}
          volumeMounts:
            {{- include "neo4j.volumeMounts" .Values.volumes | indent 12 }}
            {{- if $offlineMaintenanceEnabled  }}
            {{- include "neo4j.maintenanceVolumeMounts" .Values.volumes | indent 12 }}
            {{- end }}
            - mountPath: "/config/neo4j.conf"
              name: neo4j-conf
            {{- if .Values.ssl.bolt.privateKey.secretName }}
            - name: bolt-cert
              mountPath: /var/lib/neo4j/certificates/bolt/public.crt
              subPath: "{{ .Values.ssl.bolt.publicCertificate.subPath | default "public.crt" }}"
              readOnly: true
            - name: bolt-key
              mountPath: /var/lib/neo4j/certificates/bolt/private.key
              subPath: "{{ .Values.ssl.bolt.privateKey.subPath | default "private.key"  }}"
              readOnly: true
            {{ end }}
            {{- if .Values.ssl.https.privateKey.secretName }}
            - name: https-cert
              mountPath: /var/lib/neo4j/certificates/https/public.crt
              subPath: "{{ .Values.ssl.https.publicCertificate.subPath | default "public.crt"  }}"
              readOnly: true
            - name: https-key
              mountPath: /var/lib/neo4j/certificates/https/private.key
              subPath: "{{ .Values.ssl.https.privateKey.subPath | default "private.key" }}"
              readOnly: true
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- if $offlineMaintenanceEnabled }}
          # liveness and startup probes are disabled in offlineMaintenanceMode
          {{- else }}
          livenessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          startupProbe:
            tcpSocket:
              port: 7687
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          {{- end }}
      volumes:
        {{- /* neo4j.conf settings. Using a projected volume allows keys defined later in the list of configMaps to override keys defined earlier in the list of configmaps. */}}
        - name: neo4j-conf
          projected:
            defaultMode: 0440
            sources:
              - configMap:
                  name: "{{ .Release.Name }}-default-config"
              - configMap:
                  name: "{{ .Release.Name }}-user-config"
              - configMap:
                  name: "{{ .Release.Name }}-k8s-config"
        {{- if ( or .Values.ssl.bolt.privateKey.secretName .Values.ssl.bolt.publicCertificate.secretName ) }}
        - name: bolt-cert
          secret:
            secretName: "{{ required "When ssl.bolt.publicCertificate is set then ssl.bolt.privateKey.secretName must also be provided" .Values.ssl.bolt.publicCertificate.secretName }}"
        - name: bolt-key
          secret:
            secretName:  "{{ required "When ssl.bolt.privateKey is set then ssl.bolt.publicCertificate.secretName must also be provided" .Values.ssl.bolt.privateKey.secretName }}"
        {{- end }}
        {{- if ( or .Values.ssl.https.privateKey.secretName .Values.ssl.https.publicCertificate.secretName ) }}
        - name: https-cert
          secret:
            secretName: "{{ required "When ssl.https.publicCertificate is set then ssl.https.privateKey.secretName must also be provided" .Values.ssl.https.publicCertificate.secretName }}"
        - name: https-key
          secret:
            secretName: "{{ required "When ssl.https.privateKey is set then ssl.https.publicCertificate.secretName must also be provided" .Values.ssl.https.privateKey.secretName }}"
        {{- end }}
        {{- include "neo4j.volumes" . | nindent 8 }}
  {{- $volumeClaimTemplates := include "neo4j.volumeClaimTemplates" .}}
  {{- if $volumeClaimTemplates }}
  volumeClaimTemplates: {{ $volumeClaimTemplates | nindent 4 }}
  {{- end }}
