{{- $clusterEnabled := or ( index .Values.config "dbms.mode" | default "" | regexMatch "(?i)core|replica" ) ( index .Values.config "dbms.clustering.enable" | default "" | regexMatch "(?i)true|yes" ) }}
{{- if $clusterEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app: "{{ template "neo4j.appName" $ }}"
    {{- include "neo4j.labels" $.Values.neo4j | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-service-reader"
  labels:
    app: "{{ template "neo4j.appName" $ }}"
    {{- include "neo4j.labels" $.Values.neo4j | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-service-binding"
  labels:
    app: "{{ template "neo4j.appName" $ }}"
    {{- include "neo4j.labels" $.Values.neo4j | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role # this must be Role or ClusterRole
  name: {{ .Release.Name }}-service-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
{{- end }}
