{{- $isEnterprise := required "neo4j.edition must be specified" .Values.neo4j.edition | regexMatch "(?i)enterprise" -}}
{{- $clusterEnabled := or ( index .Values.config "dbms.mode" | default "" | regexMatch "(?i)core|replica" ) ( index .Values.config "dbms.clustering.enable" | default "" | regexMatch "(?i)true|yes" ) }}
{{- $authDisabled := index .Values.config "dbms.security.auth_enabled" | default "" | regexMatch "(?i)no|false" -}}
{{- $offlineMaintenanceEnabled :=  .Values.neo4j.offlineMaintenanceModeEnabled }}
{{- $neo4jImage := include "neo4j.image" . }}

{{- template "podSpec.checkLoadBalancerParam" . -}}
{{- template "neo4j.checkLicenseAgreement" . -}}
{{- template "neo4j.volumes.validation" . -}}
{{- template "neo4j.checkResources" . -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    helm.neo4j.com/neo4j.name: "{{ template "neo4j.name" $ }}"
    helm.neo4j.com/dbms.mode: "{{ index $.Values.config "dbms.mode" | default "SINGLE" | upper }}"
    app: "{{ template "neo4j.appName" . }}"
    helm.neo4j.com/instance: "{{ .Release.Name }}"
    {{- include "neo4j.labels" $.Values.neo4j | nindent 4 }}
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  serviceName: "{{ .Release.Name }}"
  podManagementPolicy: "Parallel" # This setting means that the StatefulSet controller doesn't block applying changes until the existing Pod is READY.
  replicas: 1
  selector:
    matchLabels:
      app: "{{ template "neo4j.appName" . }}"
      helm.neo4j.com/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ template "neo4j.appName" $ }}"
        helm.neo4j.com/neo4j.name: "{{ template "neo4j.name" $ }}"
        helm.neo4j.com/dbms.mode: "{{ index $.Values.config "dbms.mode" | default "SINGLE" | upper }}"
        helm.neo4j.com/pod_category: "neo4j-instance" # used for anti affinity rules
        helm.neo4j.com/neo4j.loadbalancer: "{{ $.Values.podSpec.loadbalancer }}"
        helm.neo4j.com/instance: "{{ .Release.Name }}"
        {{- include "neo4j.labels" $.Values.neo4j | nindent 8 }}
      annotations:
        "checksum/{{ .Release.Name }}-config": {{ include (print $.Template.BasePath "/neo4j-config.yaml") . | sha256sum }}
    spec:
      {{- if .Values.podSpec.podAntiAffinity }}
      affinity:
        {{- if kindIs "bool" .Values.podSpec.podAntiAffinity | and .Values.podSpec.podAntiAffinity }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: "{{ template "neo4j.appName" . }}"
                  helm.neo4j.com/pod_category: "neo4j-instance"
              topologyKey: kubernetes.io/hostname
        {{- else }}
        podAntiAffinity: {{ toYaml .Values.podSpec.podAntiAffinity | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if $.Values.podSpec.serviceAccountName | or $clusterEnabled }}
      serviceAccountName: "{{ if kindIs "string" $.Values.podSpec.serviceAccountName | and $.Values.podSpec.serviceAccountName }}{{ $.Values.podSpec.serviceAccountName }}{{ else }}{{ .Release.Name }}{{ end }}"
      {{- end }}
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ if $offlineMaintenanceEnabled  }}0{{ else }}{{ .Values.podSpec.terminationGracePeriodSeconds }}{{ end }}
      {{- $initContainers := .Values.podSpec.initContainers }}
      {{- $initChmodContainer := include "neo4j.initChmodContainer" . }}
      {{- if $initChmodContainer }}{{ $initContainers = fromYaml $initChmodContainer | prepend $initContainers }}{{ end }}
      {{- with $initContainers }}
      initContainers:
        {{- range $i, $initContainer := . }}
        {{- if not $offlineMaintenanceEnabled | or $initContainer.enabledInOfflineMaintenanceMode }}
        - {{ omit $initContainer "enabledInOfflineMaintenanceMode" | toYaml | indent 10 | trimAll " " }}
          {{- if not ( hasKey $initContainer "image") }}
          image: "{{ $neo4jImage }}"
          {{- end }}
          {{- if not ( hasKey $initContainer "volumeMounts") }}
          volumeMounts: {{ include "neo4j.volumeMounts" ( omit $.Values.volumes "logs" "metrics" ) | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: "neo4j"
          image: "{{ $neo4jImage }}"
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          {{- if $offlineMaintenanceEnabled }}
          command:
            - "bash"
            - "-c"
            - "while true; do echo 'Neo4j is not running. Pod is in offline maintenance mode. Remove neo4j.offlineMaintenanceModeEnabled setting and run `helm upgrade ...` to resume normal operation.'; sleep 60; done"
          {{- end }}
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-env"
            {{- if not $authDisabled }}
            - secretRef:
                name: "{{ template "neo4j.appName" . }}-auth"
            {{- end }}
          env:
            - name: HELM_NEO4J_VERSION
              value: "{{ .Values.neo4j.version | default .Chart.AppVersion }}"
            - name: HELM_CHART_VERSION
              value: "{{ .Chart.Version }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NEO4J_ADMIN
              value: "{{ .Release.Name }}-admin.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
            - name: SERVICE_NEO4J_INTERNALS
              value: "{{ .Release.Name }}-internals.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
            - name: SERVICE_NEO4J
              value: "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
            - containerPort: 6362
              name: backup
          {{- with .Values.neo4j.resources }}
          resources:
            {{- if hasKey . "requests" | or (hasKey . "limits") }}
            {{- omit . "cpu" "memory" | toYaml | nindent 12 }}
            {{- else }}
            requests: {{ . | toYaml | nindent 14 }}
            limits: {{ . | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
          securityContext: {{ omit .Values.securityContext "fsGroupChangePolicy" "fsGroup" | toYaml  | nindent 14 }}
          volumeMounts:
            - mountPath: "/config/neo4j.conf"
              name: neo4j-conf
            {{- include "neo4j.volumeMounts" .Values.volumes | indent 12 }}
            {{- include "neo4j.ssl.volumeMountsFromSecrets" .Values.ssl | indent 12 }}
            {{- if $offlineMaintenanceEnabled  }}
            {{- include "neo4j.maintenanceVolumeMounts" .Values.volumes | indent 12 }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- if $offlineMaintenanceEnabled }}
          # liveness and startup probes are disabled in offlineMaintenanceMode
          {{- else }}
          livenessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          startupProbe:
            tcpSocket:
              port: 7687
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          {{- end }}
        {{- with .Values.podSpec.containers }}
        # Extra "sidecar" containers
        {{- range $i, $extraContainer := . }}
        {{- if not $offlineMaintenanceEnabled | or $extraContainer.enabledInOfflineMaintenanceMode }}
        - {{ omit $extraContainer "enabledInOfflineMaintenanceMode" | toYaml | indent 10 | trimAll " " }}
          {{- if not ( hasKey $extraContainer "image") }}
          image: "{{ $neo4jImage }}"
          {{- end }}
          {{- if not ( hasKey $extraContainer "volumeMounts") }}
          volumeMounts: {{ include "neo4j.volumeMounts" ( omit $.Values.volumes "logs" "metrics" ) | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      volumes:
        {{- /* neo4j.conf settings. Using a projected volume allows keys defined later in the list of configMaps to override keys defined earlier in the list of configmaps. */}}
        - name: neo4j-conf
          projected:
            defaultMode: 0440
            sources:
              - configMap:
                  name: "{{ .Release.Name }}-default-config"
              - configMap:
                  name: "{{ .Release.Name }}-user-config"
              - configMap:
                  name: "{{ .Release.Name }}-k8s-config"
        {{- with include "neo4j.ssl.volumesFromSecrets" .Values.ssl }}{{ nindent 8 .}}{{ end -}}
        {{- with include "neo4j.volumes" . }}{{ nindent 8 . }}{{ end -}}
  {{- $volumeClaimTemplates := include "neo4j.volumeClaimTemplates" . -}}
  {{- if $volumeClaimTemplates }}
  volumeClaimTemplates: {{ $volumeClaimTemplates | nindent 4 }}
  {{- end }}
