# Shared neo4j object
neo4j:
  # neo4j.name is required and must match the name of the neo4j instances this service should use
  name: "neo4j-loadbalancer"
  edition: "enterprise"

# Annotations for the external service
annotations: { }

# Neo4j ports to include in external service
ports:
  http:
    enabled: true #Set this to false to remove HTTP from this service (this does not affect whether http is enabled for the neo4j process)
    # uncomment to publish http on port 80 (neo4j default is 7474)
    # port: 80
    # targetPort: 7474
    # name: "http"
    #
    # if type is NodePort, uncomment to explicitly specify the nodePort to publish http
    # nodePort: 30474
  https:
    enabled: true #Set this to false to remove HTTPS from this service (this does not affect whether https is enabled for the neo4j process)
    # uncomment to publish https on port 443 (neo4j default is 7473)
    # port: 443
    # targetPort: 7473
    # name: "https"
    #
    # if type is NodePort, uncomment to explicitly specify the nodePort to publish https
    # nodePort: 30473
  bolt:
    enabled: true #Set this to false to remove BOLT from this service (this does not affect whether https is enabled for the neo4j process)
    # Uncomment to explicitly specify the port to publish Neo4j Bolt (7687 is the default)
    # port: 7687
    # targetPort: 7687
    # name: "tcp-bolt"
    #
    # if type is NodePort, uncomment to explicitly specify the nodePort to publish Neo4j Bolt
    # nodePort: 30687
  backup:
    enabled: false #Set this to true to expose backup port externally (n.b. this could have security implications. Backup is not authenticated by default)
    # Uncomment to explicitly specify the port to publish Neo4j Backup (6362 is the default)
    # port: 6362
    # targetPort: 6362
    # name: "tcp-backup"
    #
    # if type is NodePort, uncomment to explicitly specify the nodePort to publish Neo4j Backup
    # nodePort: 30362

# A "helm.neo4j.com/neo4j.name" will be applied automatically from `neo4j.name`.
# Specify *additional* selectors to apply here (generally not required).
# If you do not want the automatic selector rename to "selectorOverride" and no "helm.neo4j.com/neo4j.name" will be applied.
selector:
  "helm.neo4j.com/neo4j.loadbalancer": "include"
  # for neo4j cluster enable this selector
  # helm.neo4j.com/clustering: "true"

# Add additional Service.spec here if needed
spec:
  type: LoadBalancer
  # in most cloud environments LoadBalancer type will receive an ephemeral public IP address automatically.
  # If you need to specify a static ip here use:
  #loadBalancerIP: ...

# Kubernetes cluster domain suffix
clusterDomain: "cluster.local"

#this flag allows you to open internal neo4j ports necessary in multi zone /region neo4j cluster scenario
multiCluster: false
