{{- with .Values.data }}
{{- if or .gcePersistentDisk .storageClassName -}}
kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  # n.b. persistent volumes don't seem to belong to namespaces
  name: "{{ $.Release.Name }}"
  labels:
    # the app name is used to link this persistent volume to the Neo4j StatefulSet
    app: "{{ template "neo4j.appName" $ }}"
    helm.neo4j.com/volume-role: "data"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "{{ required "data.capacity.storage must be set explicitly" .capacity.storage }}"
  gcePersistentDisk:
    pdName: "{{ required "data.gcePersistentDisk is required (e.g. my-disk)" .gcePersistentDisk }}"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ .storageClassName }}"
{{- if .createPersistentVolumeClaim}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $.Release.Name }}"
  labels:
    helm.neo4j.com/volume-role: "data"
    app: "{{ template "neo4j.appName" $ }}"
spec:
  storageClassName: "{{ .storageClassName }}"
  volumeName: "{{ $.Release.Name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ required "data.capacity.storage must be set explicitly" .capacity.storage }}"
{{- end }}
{{- end }}
{{- end }}
