{{- if $.Values.reverseProxy.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "neo4j.fullname" . }}-reverseproxy-ingress
  namespace: "{{ .Release.Namespace }}"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ include "neo4j.fullname" . }}-reverseproxy-service
                port:
                  number: {{ atoi $.Values.reverseProxy.port }}
            path: /
{{- end -}}
