{{- $port := include "neo4j.reverseProxy.port" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy-dep
  labels:
    name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy-dep
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy
  template:
    metadata:
      name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy
      labels:
        name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy
        {{- include "neo4j.reverseProxy.labels" $.Values.reverseProxy.podLabels | indent 8 }}
    spec:
      securityContext: {{ toYaml .Values.reverseProxy.podSecurityContext | nindent 8 }}
      {{- include "neo4j.reverseProxy.nodeSelector" . | nindent 6 }}
      {{- include "neo4j.reverseProxy.tolerations" . | nindent 6 }}
      {{- if .Values.reverseProxy.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.reverseProxy.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy
          image: {{ $.Values.reverseProxy.image }}
          imagePullPolicy: Always
          securityContext: {{ toYaml .Values.reverseProxy.containerSecurityContext | nindent 12 }}
          ports:
            - containerPort: {{ $port }}
          env:
            - name: SERVICE_NAME
              value: {{ $.Values.reverseProxy.serviceName }}
            - name: PORT
              value: {{ add $port 8000 | quote }}
            - name: DOMAIN
              value: {{ $.Values.reverseProxy.domain | default "cluster.local" }}
            - name: NAMESPACE
              value: {{ $.Values.reverseProxy.namespace | default .Release.Namespace }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.reverseProxy.resources }}
          resources:
            {{- if or (hasKey . "limits") (hasKey . "requests") }}
            {{- omit . "cpu" "memory" | toYaml | nindent 12 }}
            {{- else }}
            requests: {{ . | toYaml | nindent 14 }}
            limits: {{ . | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.extraVolumes }}
      volumes:
        {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy-service
  namespace: "{{ .Release.Namespace }}"
  {{- include "neo4j.reverseProxy.annotations" $.Values.reverseProxy.service.annotations | indent 2 }}
spec:
  type: ClusterIP
  selector:
    name: {{ include "neo4j.reverseProxy.fullname" . }}-reverseproxy
  ports:
    - protocol: TCP
      port: {{ $port }}
      targetPort: {{ add $port 8000 }}
---
