apiVersion: v1
kind: Pod
metadata:
  name: {{ include "neo4j.fullname" . }}-reverseproxy
  labels:
    name: {{ include "neo4j.fullname" . }}-reverseproxy
  namespace: "{{ .Release.Namespace }}"
spec:
  containers:
    - name: {{ include "neo4j.fullname" . }}-reverseproxy
      image: {{ $.Values.reverseProxy.image }}
      imagePullPolicy: Always
      ports:
        - containerPort: {{ atoi $.Values.reverseProxy.port }}
      env:
        - name: SERVICE_NAME
          value: {{ $.Values.reverseProxy.serviceName }}
        - name: PORT
          value: {{ $.Values.reverseProxy.port | quote }}
        - name: DOMAIN
          value: {{ $.Values.reverseProxy.domain | default "cluster.local" }}
        - name: NAMESPACE
          value: {{ $.Values.reverseProxy.namespace | default "default" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}-reverseproxy-service
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    name: {{ include "neo4j.fullname" . }}-reverseproxy
  ports:
    - protocol: TCP
      port: {{ atoi $.Values.reverseProxy.port }}
      targetPort: {{ atoi $.Values.reverseProxy.port }}
---

